import type { Property } from '@/types/property';

/** A plain, unremarkable property. Override only what a test is actually about. */
export function makeProperty(over: Partial<Property> = {}): Property {
  return {
    id: 'test',
    deal: 'sale',
    price: 2_000_000,
    source: 'test',
    publishedAt: '2026-08-01',
    daysOnMarket: 30,
    publisherKind: 'agency',
    agentFeePct: 2,
    priceDrop: 0,
    availableFrom: 'מיידי',
    city: 'חיפה',
    neighborhood: 'אחוזה',
    street: 'חורב 1',
    gush: 10812,
    helka: 57,
    tatHelka: 1,
    walkTransitMin: 5,
    walkSchoolMin: 5,
    walkParkMin: 5,
    assetType: 'apartment',
    rooms: 4,
    sqm: 100,
    balconySqm: 10,
    lotSqm: null,
    floor: 2,
    floorsInBuilding: 4,
    builtYear: 2000,
    condition: 'kept',
    aspects: 'דרום',
    features: {
      elevator: true,
      parking: 1,
      storage: false,
      mamad: true,
      ac: 'מרכזי',
      accessible: true,
      furnished: false,
      bars: false,
      separateEntrance: false,
    },
    registryKind: 'tabu',
    tenure: 'ownership',
    leaseEndsAt: null,
    caveats: 0,
    mortgages: 0,
    registryVerified: true,
    splitPermit: null,
    urbanRenewal: null,
    renewalStage: null,
    bettermentRisk: 'low',
    areaMedianPpsm: 20_000,
    areaMedianRent: 5_000,
    expectedMonthlyRent: 5_000,
    comparables: [],
    marketAsOf: '2026-09-01',
    marketSourceId: 'manual',
    marketStatus: 'manual',
    marketSampleSize: 0,
    marketFetchedAt: null,
    arnona: 500,
    vaad: 200,
    utilities: 300,
    depositMonths: 2,
    minLeaseMonths: 12,
    petsAllowed: false,
    fairRentLaw: true,
    ...over,
  };
}
